app/components/IconBoxAndLabel.tsx
app/features/oneClick/useCases/getOneClickUseCase.ts
app/libs/driver/index.ts
app/libs/driver/style.css
app/routes/account.tsx
app/routes/index.tsx
app/routes/personal-information.tsx
app/routes/verified.tsx
package-lock.json
package.json

[Ticket](https://trello.com/c/dv6ydyLd/6662-add-account-page-to-1-click-signup-demo-that-shows-shared-data)
Added account page and added tour through dashboard explaining button actions.
- added account page

feat: account page

---

server.js

[Ticket]()
Allow verified.inc and verifiedinc.webflow.io to frame the demo.
- updated CSP directives
N/A

chore: allow verified inc and webflow subdomain framing ancestor

---

.circleci/config.yml

[CI] update to use new deployment name
- ci updated with new deployment name
- test ci branch

[CI] update to use new deployment name

---

server.js

[Ticket]()
Updated the frame ancestor allowance for `verifiedinc.design.webflow.com`.
- updated CSP directive frame-ancestor
N/A

chore: update the design webflow domain

---

app/routes/register.tsx

[Ticket]()
Fix a bug that always was formatting the `birthDate` field when it should be undefined.
- updated action

fix: format conditionally dob

---

app/Layout.tsx
app/components/PhoneInput.tsx
app/features/register/components/OneClickForm.tsx
app/features/register/components/OneClickFormNonHosted.tsx
app/features/register/components/OneClickPoweredBy.tsx
app/hooks/useFullName.ts
app/root.tsx
app/routes/index.tsx
app/routes/register.tsx
app/routes/verified.tsx
app/session.server.ts

[Ticket]()
Updated the document head to include the open graph title and image. I also added the hack to scroll to the top when the input focus gets initially focused. And link powered by Verified Inc. to the main website.
- updated root
- updated form

chore: add og, input hack to scroll to top and link powered by

---

app/features/register/components/OneClickSMSDialogContent.tsx

[Ticket]()
Replace any existing http protocol to https.
- socket handler
N/A

fix: enforce https protocol when redirecting to comply with Mixed Content error

---

app/root.tsx

[Ticket]()
Update OG image.
- updated root

chore: update og

---

app/routes/verified.tsx

[Ticket](https://trello.com/c/PzGSJ57E/6708-add-see-account-button-on-success-page)
Add the **See Account** button to redirect the user to the account page.
- updated verified page

chore: add see account button

---

app/validations/birthDate.schema.ts

fix: create date instance using fixed value compliant with Safari

---

app/coreAPI.server.ts

[Ticket]()
Capture creates a 1CS response error.
- updated core api module

chore: capture one click error

---

app/Layout.tsx
app/components/FileBugButton.tsx
app/routes/bugReport.submitted.tsx
app/routes/bugReport.tsx
app/validations/bugReport.schema.ts
app/validations/description.schema.ts

[Ticket](https://trello.com/c/lqYmbjhv/6731-ability-to-report-bugs-in-1cs)
Add file bug feature.
- added page to file bugs

feat: add bug report

---

app/routes/account.tsx

[Ticket]()
SSN on the account page now displays it securely with the last five digits being visible only.
- updated field render
Tested locally

chore: commit first 5 digits for ssn field

---

app/Layout.tsx

Remove book a call button.
[Ticket](https://trello.com/c/6jCEhANE/6766-remove-book-a-call-from-1-cs-demo)
- remove button from layout

chore: remove book a call from layout

---

app/validations/birthDate.schema.ts

Fix full dob field pattern.
[Ticket]()
- fixed regex

fix: add correct regex pattern for full dob

---

app/routes/personal-information.tsx

Use correct array dependencies for memo hook.
[Ticket]()
- updated redirect url memo

fix: attempt to fix redirect url

---

Dockerfile

Updates docker command order.
[Ticket]()

refactor: update docker command

---

app/routes/favicon.tsx

Brand favicon with multi env context.
[Ticket]()

fix: brand favicon

---

package.json

Generate prisma client on migrate script.
[Ticket]()

fix: prisma generate on db migration

---

.eslintrc.js
.gitignore
.prettierignore
.trunk/trunk.yaml
prisma/schema.prisma
prisma/state.ts

Generate client locally.
[Ticket]()

chore: generate client locally

---

Dockerfile

refactor: generate prisma client docker

---

Dockerfile

fix: add correct command

---

Dockerfile
README.md
package.json

Apply prisma client generation and migration in dockerfile.
[Ticket]()
- updated dockerfile
- updated readme
Tested locally with a clean database image.

feat: update to generate Prisma client and run migrations in production

---

app/features/customConfig/components/CustomizableDialog/index.tsx
app/utils/getBrandSet.ts

fix: oneClick demo dialog and ApiKey

---

app/Layout.tsx
app/coreAPI.server.ts
app/features/oneClick/mappers/mapOneClickOptions.ts
app/routes/favicon.tsx
app/routes/register.tsx
app/utils/getBrandSet.ts

[State] set in redirectUrl.

---

app/coreAPI.server.ts
app/features/customConfig/components/CustomizableDialog/index.tsx

Redirect fixed to use /verified path and small logging improvement. Address this bug report https://verified-inc.slack.com/archives/CMM2E2AQN/p1715721262324559
- [Logging] improved.
- [RedirectUrl] fixed to only included origin and /verified path
- in dev via teset-ci

[Redirect] fixed and small logging improvement

---

app/Layout.tsx
app/components/Tip.tsx
app/features/customConfig/components/CustomizeButton.tsx

chore: add customize button and tooltip for mobile

---

app/routes/personal-information.tsx

fix: non-hosted redirect url to use the presentationRequests
https://verified-inc.slack.com/archives/CMHP6C3MY/p1716238536392439?thread_ts=1715986793.170589&cid=CMHP6C3MY

fix: non-hosted redirect url to use use the presentationRequests

---

app/routes/personal-information.tsx

Fix redirection of personal information page to verified page.
[Ticket]()
- updated navigation url

fix: redirect non-hosted cta to redirect to verified page

---

app/utils/credential.ts

fix: display ssn term

---

app/features/customConfig/components/CustomizableDialog/components/CustomizeStep.tsx
app/features/customConfig/components/CustomizableDialog/components/EnvironmentStep.tsx

Remove isValid check since it conflicts with default values.
[Ticket]()
- updated disable condition

fix: remove is valid

---

app/features/customConfig/components/CustomizableDialog/components/EnvironmentStep.tsx

Update environment enum to correct one.
[Ticket]()
- fix enum

fix: rename value

---

app/features/customConfig/components/CustomizableDialog/components/DataFieldDeleteModal.tsx

Change styles from the buttons in delete data field dialog.
[Ticket](https://trello.com/c/ptphdMhu/6875-update-delete-data-field-confirmation-dialog-to-have-delete-button-in-red-on-the-right-and-dont-delete-button-in-gray-on-the-lef)
- update styles

refactor: update styles from the delete buttons dialog

---

app/features/customConfig/components/CustomizableDialog/components/DataFieldAccordion.tsx
app/features/customConfig/components/CustomizableDialog/components/DataFieldOptionType.tsx

UI Improvements for Empty Data Fields - The default style and title for empty data fields have been updated for better user experience and visual consistency.  
Auto-Scroll to New Data Fields - The application now automatically scrolls to a newly created data field, improving usability, especially when dealing with numerous data fields.
[Ticket](https://trello.com/c/c6jbJd10/6876-update-ux-when-a-new-data-field-is-added)
- updated default data field style
- updated user experience when adding new data fields

update ux data field section

---

app/features/personalInformation/hooks/usePersonalInformationFields.ts

Use the same mask pattern as wallet.
[Ticket]()
- updated mask

fix: change mask pattern

---

app/features/customConfig/components/CustomizableDialog/components/CredentialRequestsField.tsx
app/features/customConfig/components/CustomizableDialog/index.tsx

fix: add default values

---

app/features/customConfig/components/CustomizableDialog/index.tsx
app/features/request/CredentialsDisplay/CredentialsDisplayContext.tsx
app/features/request/DataField/DataFieldHeader/HeaderSelect/index.tsx
app/features/request/request/RequestBody.tsx
app/routes/account.tsx
app/routes/personal-information.tsx

It fixes the CSS selector for the dialog's paper max-width. Add credential requests to personal information to let users input values. Validate form values.
[Ticket]()
- updated personal-information page form
- updated customized dialog

small fixes

---

app/features/request/request/RequestBody.tsx

Add a condition to render extra component as is optional.
[Ticket]()
- added conditional render

fix: conditionally render extra component

---

.circleci/config.yml

[CI] sentry org name fix. Orb bumped to latest version too.

[CI] sentry org name fix
